const slides = [
  {
    id: 1,
    type: 'title',
    title: '软件定义汽车时代',
    subtitle: '奔驰的机遇与挑战',
    layout: 'center',
    image: null,
    note: '60 分钟演讲 + 30 分钟交流。听众：商学院背景，关注组织、管理、战略转型话题。',
  },
  {
    id: 2,
    type: 'content',
    title: '今天的结构',
    content: [
      '开场：破冰 + 个人背景（3 min）',
      '第一部分：燃油车时代的黄金秩序（10 min）',
      '第二部分：电动化 + 软件化如何撕裂旧秩序（15 min）',
      '第三部分：亲历奔驰的转型之路（25 min）',
      '第四部分：反思与启示（5 min）',
      '收尾：总结 + 过渡到 Q&A（2 min）',
    ],
    layout: 'left',
    image: null,
    note: '对应 ppt-content.md 的整体结构。',
  },
  {
    id: 3,
    type: 'chapter',
    title: '开场',
    subtitle: '破冰 + 个人背景',
    layout: 'center',
    image: null,
    note: '预计 3 分钟。',
  },
  {
    id: 4,
    type: 'content',
    title: '我的角色',
    content: [
      '前奔驰研发部门，自动驾驶大部门，EE 测试集成团队',
      '我们的工作：域控制器（DCU）开发的云平台',
      '将按功能类型集成的 DCU 集中维护管理',
      '让全球开发者远程预定开发设备，支持手动开发或自动化流水线测试',
      '覆盖奔驰所有域控制器',
      '见证奔驰第一代自研 MMA 平台从 0 到 1 的全过程',
    ],
    layout: 'left',
    image: null,
    note: '个人背景与可信度建设，强调一手经历。',
  },
  {
    id: 5,
    type: 'content',
    title: '核心问题',
    content: [
      '一家 130 年历史的豪华汽车公司，为什么必须变成一家软件公司？',
      '这个转型有多难？',
    ],
    layout: 'center',
    image: null,
    note: '作为全场主线问题，后面所有章节都服务于回答它。',
  },
  {
    id: 6,
    type: 'chapter',
    title: '第一部分',
    subtitle: '燃油车时代的「黄金秩序」',
    layout: 'center',
    image: null,
    note: '预计 10 分钟。',
  },
  {
    id: 7,
    type: 'content',
    title: '三大件决定一切',
    content: [
      '燃油车时代，决定车辆体验和差异化的核心是发动机、变速箱、底盘',
      'OEM 牢牢掌握话语权，构建 Tier1 → Tier2 → Tier3 的金字塔体系',
      '动力总成约占整车成本 22-28%，底盘系统约占 10-12%',
      '三大件合计占比超过 30%，是价值最集中的区域',
      'OEM 的角色：提供标准，不负责开发，具体实现交给 Tier1',
    ],
    layout: 'left',
    image: null,
    note: 'PPT 建议：画 Tier1/2/3 金字塔结构图，标注 OEM 站在塔尖。',
  },
  {
    id: 8,
    type: 'content',
    title: '电气化 ≠ 智能化',
    content: [
      '燃油车并非没有电子系统：一辆豪华车搭载 80-120 个 ECU，奔驰 S 级可达 100+',
      '各 ECU 通过 CAN/LIN/FlexRay 总线进行信号传输',
      'OEM 的核心逻辑延续：组件按照标准工作即可，不关心内部如何开发',
      '致命问题：每个 ECU 对 OEM 来说都是「黑盒」',
      '车辆出厂后功能即锁定，用户拿到车的那一刻功能价值达到顶点，此后只会随时间下降',
    ],
    layout: 'left',
    image: null,
    note: 'PPT 建议：画价值曲线，X 轴时间，Y 轴功能价值，燃油车持续向下。',
  },
  {
    id: 9,
    type: 'chapter',
    title: '第二部分',
    subtitle: '两股力量撕裂旧秩序',
    layout: 'center',
    image: null,
    note: '预计 15 分钟。',
  },
  {
    id: 10,
    type: 'content',
    title: '电动化：价值锚点被重置',
    content: [
      '燃油车价值锚点：排量、马力、声浪、操控质感',
      '电动车价值锚点：续航里程、百公里加速、充电速度、智能座舱',
      '发动机 + 变速箱约占 30% 成本',
      '动力电池 + 电机 + 电控占 45-55% 成本',
      '决定体验和成本的位置变了，旧秩序的支点也随之移动',
    ],
    layout: 'left',
    image: null,
    note: '可做燃油车价值锚点 vs 电动车价值锚点的对照表。',
  },
  {
    id: 11,
    type: 'content',
    title: '电池成为新的成本核心',
    content: [
      '动力电池占整车成本 35-45%，其中电芯约 25-30%',
      '电驱系统（电机 + 电控）占 8-12%',
      '电池制造需要巨大规模效应才能降本，宁德时代、LG、BYD 高度集中',
      '单 GWh 产能投资约 3-4 亿元人民币',
      '关键结论：旧核心变得不再重要，新核心超出了 OEM 的传统能力边界',
    ],
    layout: 'left',
    image: null,
    note: '强调电池不仅是零部件变化，而是能力边界变化。',
  },
  {
    id: 12,
    type: 'content',
    title: '软件化：OTA 带来根本变革',
    content: [
      'OTA（Over-The-Air）= 车辆出厂后仍能通过软件更新获得新功能和体验',
      '车辆价值不再在出厂日达到顶点，而是可以持续增长',
      '但旧模式完全无法支持 OTA',
      '100+ ECU 由不同 Tier1 以不同标准开发，对 OEM 是 100+ 黑盒',
      '即使获得源代码，技术栈、工具链、编译环境也各不相同',
    ],
    layout: 'left',
    image: null,
    note: '先讲 OTA 带来的价值变化，再讲旧架构为什么做不到。',
  },
  {
    id: 13,
    type: 'content',
    title: 'OEM 必须向上游渗透',
    content: [
      '在 ECU 层面进行自主开发，制定统一软件标准',
      '以更高集成度将相似区域的功能整合',
      '域控制器（DCU）架构取代分布式 ECU 架构',
      '一次固件刷新，可同时升级多种功能',
      '这正是我们团队在做的事',
    ],
    layout: 'left',
    image: null,
    note: 'PPT 建议：左边画分布式 ECU 架构，右边画域控制架构。',
  },
  {
    id: 14,
    type: 'content',
    title: '旧金字塔的瓦解',
    content: [
      '过去的权力结构：OEM → Tier1 → Tier2 → Tier3',
      'OEM 被迫向上游（软件/电子）渗透，与 Tier1 从甲乙方变为竞合关系',
      'OEM 被迫向下游（用户体验/数据服务）延伸，进入软件订阅、功能付费',
      '电池等新核心部件出现，OEM 对供应商的话语权下降',
      '这是整场演讲的核心框架：行业权力结构正在重组',
    ],
    layout: 'left',
    image: null,
    note: '承上启下，从行业变化进入奔驰案例。',
  },
  {
    id: 15,
    type: 'chapter',
    title: '第三部分',
    subtitle: '亲历：奔驰的转型之路',
    layout: 'center',
    image: null,
    note: '核心部分，预计 25 分钟。',
  },
  {
    id: 16,
    type: 'content',
    title: '战略选择：MMA 平台与英伟达合作',
    content: [
      '奔驰推出第一代自研 MMA 平台，决心从硬件集成者变成软件开发',
      '以自动驾驶功能为突破口，与英伟达签署战略合作协议',
      '英伟达提供硬件（Orin/DRIVE 平台）+ 软件优化',
      '奔驰制定标准、进行系统集成、共享智力成果',
      '商业条款：英伟达可从最终销售中获得利润分成',
    ],
    layout: 'left',
    image: null,
    note: 'PPT 建议：画时间线，标注合作中的关键节点和摩擦事件。',
  },
  {
    id: 17,
    type: 'content',
    title: '合作中的现实摩擦',
    content: [
      '当时的权力关系：奔驰仍处于强势地位',
      '英伟达实质上分摊了奔驰的一部分自动驾驶开发成本',
      '但双方都缺乏自动驾驶量产开发经验',
      '分工边界持续模糊，责任归属扯皮不断',
      '开发问题层出不穷，节奏被反复打乱',
      '这不是供应商管理问题，而是两个庞然大物都没有做过这件事',
    ],
    layout: 'left',
    image: null,
    note: '重点是新合作范式的实验性，而不是简单归因于供应商问题。',
  },
  {
    id: 18,
    type: 'content',
    title: '组织文化的根本冲突',
    content: [
      '奔驰的口号：「我们要成为一家软件公司！」',
      '动作：全球招聘 3000 名程序员',
      '现实：从董事会到中层管理层，几乎没有软件背景',
      '「软件驱动的开发是什么样子？」管理者自己也不清楚',
      '愿望很丰满，现实很骨感',
    ],
    layout: 'left',
    image: null,
    note: '先讲战略姿态与管理现实的落差。',
  },
  {
    id: 19,
    type: 'content',
    title: 'IG Metall 工会制度的困境',
    content: [
      '软件开发部门处于 IG Metall 工会保护下',
      '软件开发者和产线工人享有同样的劳动权益',
      '一天连续工作不能超过 10 小时，两段工作之间必须间隔至少 8 小时',
      '严格假期规定，桥日（Brueckentag）不能工作',
      '加班需要审批，周末禁止工作',
      '制度保护了人，却拖慢了软件开发的速度',
    ],
    layout: 'left',
    image: null,
    note: '工会初衷无可厚非，关键是解释制度与软件开发节奏之间的张力。',
  },
  {
    id: 20,
    type: 'content',
    title: '制造文化 vs 软件文化',
    content: [
      '汽车制造文化：流程、流程、流程，因为硬件出错成本极高',
      '软件开发文化：迭代、敏捷、快速试错，因为软件可以不断更新',
      '汽车制造重线性、瀑布式开发，软件开发重持续交付',
      '汽车制造的核心能力是供应链管理，软件开发的核心能力是架构设计与持续交付',
      '用制造 V6 发动机的流程管理写代码，必然水土不服',
    ],
    layout: 'left',
    image: null,
    note: 'PPT 建议：做汽车制造文化 vs 软件开发文化对比表。',
  },
  {
    id: 21,
    type: 'content',
    title: '工具链的缺失',
    subtitle: '「边砍柴边磨刀」',
    content: [
      '传统模式下，OEM 定标准，不做具体电气组件开发',
      'Tier1 负责具体研发，拥有全套工具链',
      '历史上，奔驰的研发工具链积累在供应商那里，不在自己手里',
      '想做软件开发，需要 CI/CD、测试环境、仿真平台、诊断工具',
      '工具链不在手里，就需要从零搭建',
    ],
    layout: 'left',
    image: null,
    note: '强调大量初期资源投入基础设施，而不是直接投入产品功能。',
  },
  {
    id: 22,
    type: 'content',
    title: '我们的角色：DCU 云平台',
    content: [
      '将所有域控制器集中维护管理',
      '搭建云平台，让全球开发者可以远程预定开发设备',
      '手动开发或自动化流水线测试，按需使用',
      '工具链能力：远程刷机（Flashing）、音视频流媒体访问',
      'CAN Bus 接口 + 信号模拟、DLT 分析（Diagnostic Log and Trace）',
      '这些是传统 Tier1 已经做了几十年的东西，但在 OEM 内部，一切从零开始',
    ],
    layout: 'left',
    image: null,
    note: 'PPT 建议：画开发者 → 云平台 → DCU 硬件池 → 工具链的流程图。',
  },
  {
    id: 23,
    type: 'content',
    title: '一段真实的开发体验',
    subtitle: '叙事高潮',
    content: [
      '此处用第一人称讲述一个 2-3 分钟的具体故事',
      '可选主题：某次因为工会规定导致关键交付延期的经历',
      '可选主题：与英伟达一次典型的合作摩擦事件',
      '可选主题：某个工具链从无到有搭建过程中的「绝望时刻」',
      '可选主题：对比在 IT 行业和汽车行业做开发的体验差异',
    ],
    layout: 'left',
    image: null,
    note: '这是全场叙事高潮，需要补入真实细节，控制在 2-3 分钟。',
  },
  {
    id: 24,
    type: 'chapter',
    title: '第四部分',
    subtitle: '反思与启示',
    layout: 'center',
    image: null,
    note: '预计 5 分钟。',
  },
  {
    id: 25,
    type: 'content',
    title: '当硬件定义价值被软件定义价值替代',
    content: [
      'OEM 被迫进入一个不擅长且不喜欢的领域',
      '供应链权力结构被重组：过去你是甲方，今天你是一起摸索的同行者',
      '不是「要不要做」的问题，而是「能不能做」的问题',
    ],
    layout: 'left',
    image: null,
    note: '反思 4.1。',
  },
  {
    id: 26,
    type: 'content',
    title: '战略与组织文化必须同步转型',
    content: [
      '你可以喊出「我们要成为软件公司」',
      '你可以招聘 3000 个程序员',
      '但如果管理层思维还在硬件时代，组织制度无法适应软件开发节奏',
      '考核激励仍然是「交付了多少辆车」而不是「交付了多少能力」',
      '这 3000 个程序员只会是 3000 个沮丧的灵魂',
    ],
    layout: 'left',
    image: null,
    note: '反思 4.2。',
  },
  {
    id: 27,
    type: 'content',
    title: '工具链与基础设施是隐形核心竞争力',
    content: [
      'OEM 传统上不碰工具链，这是 Tier1 的护城河',
      '转型时才发现：没有工具链，有想法也落不了地',
      '「边砍柴边磨刀」的代价巨大，但这是必经之路',
      '任何行业的数字化转型，基础设施缺失往往是被低估的阻力',
    ],
    layout: 'left',
    image: null,
    note: '反思 4.3。',
  },
  {
    id: 28,
    type: 'content',
    title: '合作模式的演化',
    content: [
      '从「甲乙方」到「竞合关系」：奔驰与英伟达的故事',
      '当双方都没有经验时，合作本身就是一场实验',
      '利润分成、风险共担的合作模式可能成为新常态',
    ],
    layout: 'left',
    image: null,
    note: '反思 4.4。',
  },
  {
    id: 29,
    type: 'chapter',
    title: '收尾',
    subtitle: '总结 + 过渡到 Q&A',
    layout: 'center',
    image: null,
    note: '预计 2 分钟。',
  },
  {
    id: 30,
    type: 'content',
    title: '三句话总结',
    content: [
      '燃油车时代的 OEM 是「定义者」，供应链围着转',
      '电动化 + 软件化两条线，把 OEM 同时向上游（软件）和向外（电池）推',
      '奔驰的转型展示了「战略意图 vs 组织现实」之间巨大的鸿沟',
    ],
    layout: 'left',
    image: null,
    note: '对应 ppt-content.md 的收尾总结。',
  },
  {
    id: 31,
    type: 'content',
    title: 'Q&A 引导',
    content: [
      '各位所在的行业，是否也正在经历类似的范式转移？',
      '当管理层说我们要数字化的时候，你们觉得最难的是什么？',
    ],
    layout: 'center',
    image: null,
    note: '过渡到 30 分钟交流。',
  },
  {
    id: 32,
    type: 'end',
    title: '谢谢',
    subtitle: 'Q & A',
    layout: 'center',
    image: null,
    note: '',
  },
]

export default slides
