const slides = [
  {
    id: 1,
    type: 'title',
    title: '软件定义汽车时代',
    subtitle: '奔驰的机遇与挑战',
    layout: 'center',
    image: null,
    note: '60分钟演讲 + 30分钟交流。听众：商学院背景，关注组织、管理、战略转型话题。',
  },
  {
    id: 2,
    type: 'chapter',
    title: '开场',
    subtitle: '个人背景与核心问题',
    layout: 'center',
    image: null,
    note: '预计 3 分钟',
  },
  {
    id: 3,
    type: 'content',
    title: '我的背景',
    content: [
      '研发部门，自动驾驶大部门，EE 测试集成团队',
      '工作内容：域控制器（DCU）云平台开发',
      '—— 将 DCU 集中维护管理，搭建云平台让全球开发者远程预定开发设备',
      '—— 支持手动开发或自动化流水线测试，覆盖奔驰所有域控制器',
      '见证了奔驰第一代自研 MMA 平台从 0 到 1 的全过程',
    ],
    layout: 'left',
    image: null,
    note: '介绍你和 DCU 云平台的角色。听众想了解你的权威性来源。',
  },
  {
    id: 4,
    type: 'content',
    title: '核心问题',
    content: [
      '一家 130 年历史的豪华汽车公司',
      '为什么必须变成一家软件公司？',
      '这个转型，有多难？',
    ],
    layout: 'center',
    image: null,
    note: '用这三个问题锚定整场演讲的框架',
  },
  {
    id: 5,
    type: 'chapter',
    title: '第一部分',
    subtitle: '燃油车时代的「黄金秩序」',
    layout: 'center',
    image: null,
    note: '预计 10 分钟',
  },
  {
    id: 6,
    type: 'content',
    title: '三大件决定一切',
    content: [
      '燃油车时代，决定体验和差异化的核心：发动机、变速箱、底盘',
      'OEM 牢牢掌握话语权，构建了 Tier1 → Tier2 → Tier3 的金字塔体系',
      'BOM 成本结构：动力总成 22-28% + 底盘 10-12% → 三大件合计 > 30%',
      'OEM 的角色：提供标准，不负责开发——具体实现交给 Tier1',
    ],
    layout: 'left',
    image: null,
    note: '画 Tier1/2/3 金字塔结构图，标注 OEM 站在塔尖',
  },
  {
    id: 7,
    type: 'content',
    title: '电气化 ≠ 智能化',
    content: [
      '一辆豪华车搭载 80-120 个 ECU（奔驰 S 级可达 100+）',
      '各 ECU 通过 CAN/LIN/FlexRay 总线进行信号传输',
      'OEM 核心逻辑：只要组件按标准工作，不关心内部如何开发',
      '致命问题：每个 ECU 对 OEM 都是「黑盒」，出厂后功能即锁定',
      '用户在拿到车的那一刻，车辆的功能价值即达顶点，此后只降不升',
    ],
    layout: 'left',
    image: null,
    note: '用「价值曲线」图——X 轴时间，Y 轴功能价值，燃油车是持续向下的曲线',
  },
  {
    id: 8,
    type: 'chapter',
    title: '第二部分',
    subtitle: '变局——两股力量撕裂旧秩序',
    layout: 'center',
    image: null,
    note: '预计 15 分钟',
  },
  {
    id: 9,
    type: 'content',
    title: '电动化：BOM 结构的根本颠覆',
    content: [
      '决定汽车体验的标准被重置：',
      '燃油车 → 排量、马力、声浪、操控质感',
      '电动车 → 续航里程、百公里加速、充电速度、智能座舱',
      '动力电池占整车成本 35-45%（电芯约 25-30%）',
      '单 GWh 产能投资约 3-4 亿元人民币',
      '关键结论：新的核心（电池）超出了 OEM 的能力边界',
    ],
    layout: 'left',
    image: null,
    note: '用对比表格展示燃油车 vs 电动车的价值锚点变化',
  },
  {
    id: 10,
    type: 'content',
    title: '软件化：OTA 带来的根本性变革',
    content: [
      'OTA = 车辆出厂后仍能通过软件更新获得新功能和体验',
      '车辆价值不再在出厂日达到顶点，而是可以持续增长',
      '但旧模式无法支持 OTA：100+ ECU 由不同 Tier1 开发 → 100+ 黑盒',
      '即使获得源代码，技术栈、工具链、编译环境各不相同',
      '因此 OEM 必须向上游渗透：统一软件标准，域控制器架构取代分布式 ECU',
    ],
    layout: 'left',
    image: null,
    note: '左边画分布式 ECU 架构（混乱网状），右边画域控制架构（清晰层级），形成对比',
  },
  {
    id: 11,
    type: 'content',
    title: '旧金字塔的瓦解',
    content: [
      '过去的权力结构：OEM → Tier1 → Tier2 → Tier3',
      '新的权力结构：',
      'OEM 被迫向上游（软件/电子）渗透 → 与 Tier1 从甲乙方变竞合',
      'OEM 被迫向下游（用户体验/数据）延伸 → 软件订阅、功能付费',
      '电池等新核心部件 → OEM 对供应商话语权下降',
    ],
    layout: 'left',
    image: null,
    note: '这是整场演讲的核心框架',
  },
  {
    id: 12,
    type: 'chapter',
    title: '第三部分',
    subtitle: '亲历——奔驰的转型之路',
    layout: 'center',
    image: null,
    note: '★ 核心部分，预计 25 分钟',
  },
  {
    id: 13,
    type: 'content',
    title: '战略选择：MMA 平台与英伟达合作',
    content: [
      '奔驰推出第一代自研 MMA 平台，决心从硬件集成者变成软件开发',
      '以自动驾驶功能为突破口，与英伟达签署战略合作协议',
      '合作模式：英伟达提供硬件+软件优化，奔驰制定标准、系统集成',
      '商业条款：英伟达可从最终销售中获利润分成',
      '现实摩擦：双方都缺自动驾驶量产经验，分工边界持续模糊，责任扯皮',
      '这不是供应商管理问题，而是两个庞然大物都没有做过这件事',
    ],
    layout: 'left',
    image: null,
    note: '画一条时间线，标注合作中的关键节点和摩擦事件',
  },
  {
    id: 14,
    type: 'content',
    title: '组织文化的根本冲突 (1/3)',
    content: [
      '奔驰口号：「我们要成为一家软件公司！」',
      '动作：全球招聘 3000 名程序员',
      '现实：从董事会到中层管理层，几乎没有软件背景',
      '「软件驱动的开发是什么样子？」——管理者自己也不清楚',
      '愿望很丰满，现实很骨感',
    ],
    layout: 'left',
    image: null,
    note: '管理层不懂软件，战略 vs 现实的落差',
  },
  {
    id: 15,
    type: 'content',
    title: '组织文化的根本冲突 (2/3)',
    content: [
      'IG Metall 工会制度的困境：',
      '软件开发部门处于工会保护下，和产线工人享有同样劳动权益',
      '—— 一天连续工作不能超过 10 小时，两段工作间隔至少 8 小时',
      '—— 严格假期规定，桥日（Brückentag）不能工作',
      '—— 加班需审批，周末禁止工作',
      '工会初衷：保护所有基层员工——无可厚非',
      '但软件开发本质：灵活、异步、创意驱动',
      '结果：制度保护了人，却拖慢了软件开发的速度',
    ],
    layout: 'left',
    image: null,
    note: 'IG Metall 困境的具体案例',
  },
  {
    id: 16,
    type: 'content',
    title: '组织文化的根本冲突 (3/3)',
    content: [
      '汽车制造文化：流程、流程、流程——硬件出错成本极高',
      '软件开发文化：迭代、敏捷、快速试错——软件可以不断更新',
      '用制造 V6 发动机的流程管理写代码的团队 → 必然水土不服',
    ],
    layout: 'center',
    image: null,
    note: '对比表格',
  },
  {
    id: 17,
    type: 'content',
    title: '工具链的缺失——「边砍柴边磨刀」',
    content: [
      '传统模式：OEM 定标准，Tier1 负责研发，拥有全套工具链',
      '奔驰的研发工具链积累在供应商那里，不在自己手里',
      '转型现实：想搞软件 → 需要 CI/CD、测试环境、仿真平台、诊断工具 → 都要从零搭建',
      '我们团队的角色——DCU 云平台：',
      '刷机（Flashing）、音视频流媒体、CAN Bus 接口 + 信号模拟、DLT 分析',
      '这些都是 Tier1 已做了几十年的东西，但在 OEM 内部一切从零开始',
    ],
    layout: 'left',
    image: null,
    note: '画云平台架构图，展示开发者→云平台→DCU硬件池→工具链的流程',
  },
  {
    id: 18,
    type: 'content',
    title: '一段真实的开发体验',
    subtitle: '叙事高潮',
    content: [
      '用第一人称讲述你在奔驰见证 MMA 平台从 0 到 1 的具体故事，可以是：',
      '—— 某次因工会规定导致关键交付延期的经历',
      '—— 与英伟达一次典型的合作摩擦事件',
      '—— 某个工具链从无到有搭建的「绝望时刻」',
      '—— 对比在 IT 行业和汽车行业做开发的体验差异',
    ],
    layout: 'center',
    image: null,
    note: '故事控制在 2-3 分钟，作为整个演讲的叙事高潮。建议在此处准备一个具体故事。',
  },
  {
    id: 19,
    type: 'chapter',
    title: '第四部分',
    subtitle: '反思与启示',
    layout: 'center',
    image: null,
    note: '预计 5 分钟',
  },
  {
    id: 20,
    type: 'content',
    title: '反思一：当硬件定义价值被软件定义价值替代',
    content: [
      'OEM 被迫进入一个「不擅长且不喜欢的领域」',
      '供应链权力结构被重组——过去你是甲方，今天你是「一起摸索的同行者」',
      '不是「要不要做」的问题，而是「能不能做」的问题',
    ],
    layout: 'left',
    image: null,
    note: '',
  },
  {
    id: 21,
    type: 'content',
    title: '反思二：战略与组织文化必须同步转型',
    content: [
      '可以喊出「我们要成为软件公司」，可以招聘 3000 个程序员',
      '但如果：管理层的思维方式还在硬件时代',
      '组织制度和劳动法无法适应软件开发节奏',
      '考核激励仍是「交付了多少辆车」而非「交付了多少能力」',
      '那么这 3000 个程序员只会是 3000 个沮丧的灵魂',
    ],
    layout: 'left',
    image: null,
    note: '',
  },
  {
    id: 22,
    type: 'content',
    title: '反思三：工具链与基础设施是隐形核心竞争力',
    content: [
      'OEM 传统上不碰工具链 → 这是 Tier1 的护城河',
      '转型时才发现：没有工具链，有想法也落不了地',
      '「边砍柴边磨刀」的代价巨大——但这是必经之路',
      '任何行业的数字化转型，基础设施的缺失往往是低估的阻力',
    ],
    layout: 'left',
    image: null,
    note: '',
  },
  {
    id: 23,
    type: 'content',
    title: '反思四：合作模式的演化',
    content: [
      '从「甲乙方」到「竞合关系」——奔驰与英伟达的故事',
      '当双方都没有经验时，合作本身就是一场实验',
      '利润分成、风险共担的合作模式可能成为新常态',
    ],
    layout: 'left',
    image: null,
    note: '',
  },
  {
    id: 24,
    type: 'chapter',
    title: '收尾',
    subtitle: '总结 + 过渡到 Q&A',
    layout: 'center',
    image: null,
    note: '预计 2 分钟',
  },
  {
    id: 25,
    type: 'content',
    title: '三句话总结',
    content: [
      '1. 燃油车时代的 OEM 是「定义者」，供应链围着转',
      '2. 电动化 + 软件化两条线，把 OEM 同时向上游（软件）和向外（电池）推',
      '3. 奔驰的转型展示了「战略意图 vs 组织现实」之间巨大的鸿沟',
    ],
    layout: 'left',
    image: null,
    note: 'Q&A 引导：各位所在的行业，是否也正在经历类似的范式转移？当管理层说我们要数字化的时候，你们觉得最难的是什么？',
  },
  {
    id: 26,
    type: 'end',
    title: '谢谢',
    subtitle: 'Q & A',
    layout: 'center',
    image: null,
    note: '',
  },
]

export default slides
